# Generated by Django 5.1 on 2024-08-17 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='etapafunil',
            name='nome',
            field=models.CharField(choices=[('Descoberta', 'Discovery'), ('Consideração', 'Consideration'), ('Decisão', 'Decision'), ('Pós-Venda', 'Post-Sale')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.origem'),
        ),
    ]
